<?php declare(strict_types=1);

namespace BabDev\WebSocket\Server\Tests\WAMP\Middleware;

use BabDev\WebSocket\Server\Connection;
use BabDev\WebSocket\Server\Connection\ArrayAttributeStore;
use BabDev\WebSocket\Server\Server;
use BabDev\WebSocket\Server\WAMP\Exception\InvalidMessage;
use BabDev\WebSocket\Server\WAMP\Exception\UnsupportedMessageType;
use BabDev\WebSocket\Server\WAMP\MessageType;
use BabDev\WebSocket\Server\WAMP\Middleware\ParseWAMPMessage;
use BabDev\WebSocket\Server\WAMP\Topic;
use BabDev\WebSocket\Server\WAMP\TopicRegistry;
use BabDev\WebSocket\Server\WAMP\WAMPConnection;
use BabDev\WebSocket\Server\WAMPServerMiddleware;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\TestDox;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\MockObject\Stub;
use PHPUnit\Framework\TestCase;

final class ParseWAMPMessageTest extends TestCase
{
    public function testGetSubProtocols(): void
    {
        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);

        $decoratedMiddleware->expects($this->once())
            ->method('getSubProtocols')
            ->willReturn(['ws']);

        $this->assertSame(
            ['ws', 'wamp'],
            new ParseWAMPMessage($decoratedMiddleware, $this->createStub(TopicRegistry::class))->getSubProtocols(),
        );
    }

    #[TestDox('Handles a new connection being opened')]
    public function testOnOpen(): void
    {
        $attributeStore = new ArrayAttributeStore();

        $sentData = null;

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send')
            ->willReturnCallback(static function (mixed $data) use (&$sentData): void {
                $sentData = $data;
            });

        new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class))->onOpen($connection);

        $this->assertIsString($sentData);
        $this->assertJson($sentData);

        /** @var array<int, mixed> $data */
        $data = json_decode($sentData, true, 512, \JSON_THROW_ON_ERROR);

        $this->assertSame(MessageType::WELCOME, $data[0], 'When a connection is opened, a welcome message should be sent to the connected client.');
        $this->assertSame($attributeStore->get('wamp.session_id'), $data[1], 'The welcome message should specify the session ID generated by the middleware.');
        $this->assertSame(1, $data[2], 'The correct WAMP version should be specified in the welcome message.');
        $this->assertSame(Server::VERSION, $data[3], 'The server identity should be provided by default.');
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "PREFIX" message')]
    public function testOnMessageForPrefixMessage(): void
    {
        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(4))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        $prefix = 'testing';
        $uri = 'https://example.com/testing';

        $middleware = new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::PREFIX, $prefix, $uri], \JSON_THROW_ON_ERROR));

        $this->assertSame(
            [$prefix => $uri],
            $attributeStore->get('wamp.prefixes'),
            "The prefix should be added to the connection's attributes.",
        );
    }

    /**
     * @return \Generator<string, array>
     */
    public static function dataCallMessage(): \Generator
    {
        yield 'Parameters as separate values' => [2, 'a', 'b'];

        yield 'Parameters as unkeyed array' => [2, ['a', 'b']];

        yield 'Parameters as keyed array' => [2, ['hello' => 'world', 'herp' => 'derp']];

        yield 'Parameters with multiple types when an array is not the first parameter' => [2, 'hi', ['hello', 'world']];

        yield 'Parameters with multiple types when an array is the first parameter' => [2, ['hello', 'world'], 'hi'];
    }

    #[DataProvider('dataCallMessage')]
    #[TestDox('Handles incoming data on the connection for a WAMP "CALL" message')]
    public function testOnMessageForCallMessage(mixed ...$args): void
    {
        /** @var int<0, max> $paramCount */
        $paramCount = array_shift($args);

        $uri = 'https://example.com/testing/'.random_int(1, 1000);
        $callId = uniqid();

        $message = [MessageType::CALL, $callId, $uri, ...$args];

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onCall')
            ->with($this->isInstanceOf(WAMPConnection::class), $callId, $uri, $this->isArray())
            ->willReturnCallback(static function (Connection $connection, string $id, string $resolvedUri, array $params) use ($paramCount): void {
                self::assertCount($paramCount, $params);
            });

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode($message, \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "SUBSCRIBE" message')]
    public function testOnMessageForSubscribeMessage(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&TopicRegistry $topicRegistry */
        $topicRegistry = $this->createMock(TopicRegistry::class);
        $topicRegistry->expects($this->once())
            ->method('has')
            ->with($uri)
            ->willReturn(false);

        $topicRegistry->expects($this->once())
            ->method('add')
            ->with($this->isInstanceOf(Topic::class));

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onSubscribe')
            ->with($this->isInstanceOf(WAMPConnection::class), $this->isInstanceOf(Topic::class));

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $topicRegistry);
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::SUBSCRIBE, $uri], \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "UNSUBSCRIBE" message')]
    public function testOnMessageForUnsubscribeMessage(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&TopicRegistry $topicRegistry */
        $topicRegistry = $this->createMock(TopicRegistry::class);
        $topicRegistry->expects($this->once())
            ->method('has')
            ->with($uri)
            ->willReturn(false);

        $topicRegistry->expects($this->once())
            ->method('add')
            ->with($this->isInstanceOf(Topic::class));

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onUnsubscribe')
            ->with($this->isInstanceOf(WAMPConnection::class), $this->isInstanceOf(Topic::class));

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $topicRegistry);
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::UNSUBSCRIBE, $uri], \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "PUBLISH" message with string payload and no extra params')]
    public function testOnMessageForPublishMessageWithStringPayloadNoExtraParams(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&TopicRegistry $topicRegistry */
        $topicRegistry = $this->createMock(TopicRegistry::class);
        $topicRegistry->expects($this->once())
            ->method('has')
            ->with($uri)
            ->willReturn(false);

        $topicRegistry->expects($this->once())
            ->method('add')
            ->with($this->isInstanceOf(Topic::class));

        $event = 'Simple event payload';

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onPublish')
            ->with($this->isInstanceOf(WAMPConnection::class), $this->isInstanceOf(Topic::class), $event, [], []);

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $topicRegistry);
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::PUBLISH, $uri, $event], \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "PUBLISH" message with array payload and no extra params')]
    public function testOnMessageForPublishMessageWithArrayPayloadNoExtraParams(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&TopicRegistry $topicRegistry */
        $topicRegistry = $this->createMock(TopicRegistry::class);
        $topicRegistry->expects($this->once())
            ->method('has')
            ->with($uri)
            ->willReturn(false);

        $topicRegistry->expects($this->once())
            ->method('add')
            ->with($this->isInstanceOf(Topic::class));

        $event = ['hello' => 'world', 'herp' => 'derp'];

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onPublish')
            ->with($this->isInstanceOf(WAMPConnection::class), $this->isInstanceOf(Topic::class), $event, [], []);

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $topicRegistry);
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::PUBLISH, $uri, $event], \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "PUBLISH" message with the "excludeMe" param')]
    public function testOnMessageForPublishMessageWithExcludeMeParam(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(3))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&TopicRegistry $topicRegistry */
        $topicRegistry = $this->createMock(TopicRegistry::class);
        $topicRegistry->expects($this->once())
            ->method('has')
            ->with($uri)
            ->willReturn(false);

        $topicRegistry->expects($this->once())
            ->method('add')
            ->with($this->isInstanceOf(Topic::class));

        $event = 'Simple event payload';

        $excludedSessions = [];

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onPublish')
            ->willReturnCallback(static function (Connection $connection, Topic $topic, array|string $event, array $exclude, array $eligible) use (&$excludedSessions): void {
                $excludedSessions = $exclude;
            });

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $topicRegistry);
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::PUBLISH, $uri, $event, true], \JSON_THROW_ON_ERROR));

        $this->assertSame(
            [$attributeStore->get('wamp.session_id')],
            $excludedSessions,
            'When the "excludeMe" param is provided, the user\'s connection should be in the exclude list.'
        );
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "PUBLISH" message with a list of excluded sessions')]
    public function testOnMessageForPublishMessageWithListOfExcludedSessions(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&TopicRegistry $topicRegistry */
        $topicRegistry = $this->createMock(TopicRegistry::class);
        $topicRegistry->expects($this->once())
            ->method('has')
            ->with($uri)
            ->willReturn(false);

        $topicRegistry->expects($this->once())
            ->method('add')
            ->with($this->isInstanceOf(Topic::class));

        $event = 'Simple event payload';
        $exclude = [bin2hex(random_bytes(32)), bin2hex(random_bytes(32)), bin2hex(random_bytes(32))];

        $excludedSessions = [];

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onPublish')
            ->willReturnCallback(static function (Connection $connection, Topic $topic, array|string $event, array $exclude, array $eligible) use (&$excludedSessions): void {
                $excludedSessions = $exclude;
            });

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $topicRegistry);
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::PUBLISH, $uri, $event, $exclude], \JSON_THROW_ON_ERROR));

        $this->assertSame(
            $exclude,
            $excludedSessions,
            'The list of excluded sessions should be forwarded to inner middleware.'
        );
    }

    #[TestDox('Handles incoming data on the connection for a WAMP "PUBLISH" message with a list of eligible sessions')]
    public function testOnMessageForPublishMessageWithListOfEligibleSessions(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&TopicRegistry $topicRegistry */
        $topicRegistry = $this->createMock(TopicRegistry::class);
        $topicRegistry->expects($this->once())
            ->method('has')
            ->with($uri)
            ->willReturn(false);

        $topicRegistry->expects($this->once())
            ->method('add')
            ->with($this->isInstanceOf(Topic::class));

        $event = 'Simple event payload';
        $eligible = [bin2hex(random_bytes(32)), bin2hex(random_bytes(32)), bin2hex(random_bytes(32))];

        $eligibleSessions = [];

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onPublish')
            ->willReturnCallback(static function (Connection $connection, Topic $topic, array|string $event, array $exclude, array $eligible) use (&$eligibleSessions): void {
                $eligibleSessions = $eligible;
            });

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $topicRegistry);
        $middleware->onOpen($connection);
        $middleware->onMessage($connection, json_encode([MessageType::PUBLISH, $uri, $event, [], $eligible], \JSON_THROW_ON_ERROR));

        $this->assertSame(
            $eligible,
            $eligibleSessions,
            'The list of eligible sessions should be forwarded to inner middleware.'
        );
    }

    #[TestDox('Handles incoming data on the connection for an unsupported WAMP message type')]
    public function testOnMessageForUnsupportedMessageType(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        $event = 'Simple event payload';

        $middleware = new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);

        $this->expectException(UnsupportedMessageType::class);

        $middleware->onMessage($connection, json_encode([MessageType::EVENT, $uri, $event], \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection with a message body that does not decode into an array')]
    public function testOnMessageWithNonArrayMessageType(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        $middleware = new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);

        $this->expectException(InvalidMessage::class);

        $middleware->onMessage($connection, json_encode($uri, \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection with a message body that decodes into an associative array')]
    public function testOnMessageWithAssociativeArrayMessageType(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        $middleware = new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);

        $this->expectException(InvalidMessage::class);

        $middleware->onMessage($connection, json_encode(['uri' => $uri], \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection with a message body that includes a topic URI that is not a string')]
    public function testOnMessageWithNonStringTopicUri(): void
    {
        $uri = 'https://example.com/testing/'.random_int(1, 1000);

        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        $middleware = new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);

        $this->expectException(InvalidMessage::class);

        $middleware->onMessage($connection, json_encode([MessageType::PUBLISH, [$uri], 'Testing'], \JSON_THROW_ON_ERROR));
    }

    #[TestDox('Handles incoming data on the connection with invalid JSON')]
    public function testOnMessageWithInvalidJson(): void
    {
        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        $middleware = new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);

        $this->expectException(InvalidMessage::class);

        $middleware->onMessage($connection, '"[7,["https:\/\/example.com\/testing\/255"],"Testing]"');
    }

    #[TestDox('Closes the connection')]
    public function testOnClose(): void
    {
        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onClose')
            ->with($this->isInstanceOf(WAMPConnection::class));

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);
        $middleware->onClose($connection);
    }

    #[TestDox('Forwards the decorated connection to middleware onError when a decorator is available')]
    public function testOnError(): void
    {
        $attributeStore = new ArrayAttributeStore();

        /** @var MockObject&Connection $connection */
        $connection = $this->createMock(Connection::class);
        $connection->expects($this->exactly(2))
            ->method('getAttributeStore')
            ->willReturn($attributeStore);

        $connection->expects($this->once())
            ->method('send');

        $error = new \Exception('Testing');

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onError')
            ->with($this->isInstanceOf(WAMPConnection::class), $error);

        $middleware = new ParseWAMPMessage($decoratedMiddleware, $this->createStub(TopicRegistry::class));
        $middleware->onOpen($connection);
        $middleware->onError($connection, $error);
    }

    #[TestDox('Forwards the non-decorated connection to middleware onError if a decorator is not available')]
    public function testOnErrorWithUndecoratedConnection(): void
    {
        /** @var Stub&Connection $connection */
        $connection = $this->createStub(Connection::class);

        $exception = new \Exception('Testing');

        /** @var MockObject&WAMPServerMiddleware $decoratedMiddleware */
        $decoratedMiddleware = $this->createMock(WAMPServerMiddleware::class);
        $decoratedMiddleware->expects($this->once())
            ->method('onError')
            ->with($connection, $exception);

        new ParseWAMPMessage($decoratedMiddleware, $this->createStub(TopicRegistry::class))->onError($connection, $exception);
    }

    #[TestDox('The server identity can be managed')]
    public function testServerIdentity(): void
    {
        $middleware = new ParseWAMPMessage($this->createStub(WAMPServerMiddleware::class), $this->createStub(TopicRegistry::class));

        $this->assertSame(Server::VERSION, $middleware->getServerIdentity());

        $middleware->setServerIdentity($newIdentity = 'Test-Identity/4.2');

        $this->assertSame($newIdentity, $middleware->getServerIdentity());
    }
}
