name: 'Run Tests'

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: true
      matrix:
        php: ['8.4', '8.5']
        composer-flags: ['--prefer-stable']
        can-fail: [false]
        include:
          - php: '8.4'
            composer-flags: '--prefer-stable --prefer-lowest'
            can-fail: false

    name: "PHP ${{ matrix.php }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}" # zizmor: ignore[template-injection]

    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: curl, iconv, mbstring, session, sockets, sqlite, zip
          coverage: none

      - name: Install dependencies
        run: composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest # zizmor: ignore[template-injection]

      - name: Execute tests
        run: vendor/bin/phpunit --display-deprecations
