name: 'Static Analysis'

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sa-phpstan:
    runs-on: ubuntu-latest

    name: PHPStan

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: '8.5'
          tools: composer:v2
          extensions: curl, iconv, mbstring, session, sockets, sqlite, zip
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --error-format=github
